name: Automate EMLID_PT Script

on:
  workflow_dispatch:
  schedule:
    - cron: " " 

jobs:
  run-emlid-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create credentials files from secrets
      run: |
        echo "$CLIENT_SECRETS_JSON" > client_secrets.json
        echo "$CREDENTIALS_GMAIL_JSON" > credentials_gmail.json
        echo "$TOKEN_GMAIL_JSON" > token_gmail.json
        echo "$MYCREDS_TXT" > mycreds.txt
      env:
        CLIENT_SECRETS_JSON: ${{ secrets.CLIENT_SECRETS_JSON }}
        CREDENTIALS_GMAIL_JSON: ${{ secrets.CREDENTIALS_GMAIL_JSON }}
        TOKEN_GMAIL_JSON: ${{ secrets.TOKEN_GMAIL_JSON }}
        MYCREDS_TXT: ${{ secrets.MYCREDS_TXT }}

    - name: Run EMLID_PT Script
      run: python Clip_VIW.py

